### ISSUE TITLE
Add documentation for config.json

### ISSUE THREAD

**Issue by ISNIT0** [openzim/phet#1]

**Comment by kelson42** [comment]
@midik I think one time we retrieve the language dynamically then probably `config.json` will vanish (the few things left can be put in the code), and this one would be ready to close as well.

**Comment by midik** [comment]
related to #19

**Comment by midik** [comment]
After cleaning up the config, it looks like the following:
```
module.exports = {
    "verbose": true,
    "workers": 4,
    "imageResolution": 600,
    "categoriesToGet": [
        "Physics",
        "Biology",
        "Chemistry",
        "Earth Science",
        "Math"
    ]
}
```
Would be probably a good idea to remove all of these keys except `work` because most of the steps use it. The rest keys used only on `get` step so that could be placed directly into the code. Also, I think would be good solution to move `workers` key to `.env` and then remove this config file. Is this ok?

**Comment by kelson42** [comment]
@midik Agree.

**Comment by midik** [comment]
`config.js` removed and migrated to `dotenv`
(not merged to master yet)
